modLoader = "javafml"
loaderVersion = "[47,)"
license = "All Rights Reserved"
[[mods]]
modid = "endlesschestmod"
version = "1.0.0"
displayName = "Endless Chest Mod"
authors = "kareiku"
description = "A chest capable of holding an infinite amount of items."
