modLoader="javafml"
loaderVersion="[14,)"
license="MIT"
modid="endlesschestmod"
version="1.0.0"
displayName="Endless Chest Mod"
description="A chest capable of holding an infinite amount of items."
authors="kareiku"
